spring:
  datasource:
    url: jdbc:mysql://db:3306/dangdang_check?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  logging:
    file:
      name: /app/logs/app.log  # ?? ?? ?? ??
    level:
      root: info  # ?? ?? ?? ??

