spring:
  datasource:
    url: jdbc:mysql://db:3306/dangdang_check?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false

  logging:
    file:
      name: /app/logs/app.log
    level:
      root: info
